const centreData = [
  {
    id: 1,
    name: "Winterfell",
    email: "north@email.com",
    phoneNumber: "123456789",
    contactPerson: "Ned Stark",
    address: "The North",
    tradeArea: "Killing Wildlings",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The North",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Rickard Stark",
    assessedbyOfficer1: "Brandon Stark",
    assessedbyOfficer2: "Theon Stark",
    assessedbyAOLeader: "Cregan Stark",
    assessedbyAOOfficer: "Torrhen Stark",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 2,
    name: "Casterly Rock",
    email: "westerlands@email.com",
    phoneNumber: "123456789",
    contactPerson: "Tywin Lannister",
    address: "The Westerlands",
    tradeArea: "Throne Usurpers",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Westerlands",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Jaime Lannister",
    assessedbyOfficer1: "Cersei Lannister",
    assessedbyOfficer2: "Tyrion Lannister",
    assessedbyAOLeader: "Kevan Lannister",
    assessedbyAOOfficer: "Lancel Lannister",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 3,
    name: "Pyke",
    email: "ironislands@email.com",
    phoneNumber: "123456789",
    contactPerson: "Balon Greyjoy",
    address: "The Iron Islands",
    tradeArea: "Killing families",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Iron Islands",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Theon Greyjoy",
    assessedbyOfficer1: "Victarion Greyjoy",
    assessedbyOfficer2: "Eurion Greyjoy",
    assessedbyAOLeader: "Asha Greyjoy",
    assessedbyAOOfficer: "Rodrik Greyjoy",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 4,
    name: "Riverrun",
    email: "river@email.com",
    phoneNumber: "123456789",
    contactPerson: "Hoster Tully",
    address: "The Riverlands",
    tradeArea: "Fishing",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Riverlands",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Bryden Tully",
    assessedbyOfficer1: "Hoster Tully",
    assessedbyOfficer2: "Edmure Tully",
    assessedbyAOLeader: "Lysa Tully",
    assessedbyAOOfficer: "Catlyn Tully",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 5,
    name: "Eyrie",
    email: "vale@email.com",
    phoneNumber: "123456789",
    contactPerson: "Jon Arryn",
    address: "The Vale of Arryn",
    tradeArea: "Killing Wildlings",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Vale of Arryn",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Robin Arryn",
    assessedbyOfficer1: "Artys Arryn",
    assessedbyOfficer2: "Sharra Arryn",
    assessedbyAOLeader: "Ronnel Arryn",
    assessedbyAOOfficer: "Yohn Royce",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 6,
    name: "Storm's End",
    email: "storm@email.com",
    phoneNumber: "123456789",
    contactPerson: "Robert Baratheon",
    address: "The Stormlands",
    tradeArea: "Fighting Storms",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Stormlands",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Stannis Baratheon",
    assessedbyOfficer1: "Renly Baratheon",
    assessedbyOfficer2: "Tommen Baratheon",
    assessedbyAOLeader: "Mycella Baratheon",
    assessedbyAOOfficer: "Shireen Baratheon",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 7,
    name: "Highgarden",
    email: "rose@email.com",
    phoneNumber: "123456789",
    contactPerson: "Loras Tyras",
    address: "The Reach",
    tradeArea: "Growing Strong",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Reach",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Mace Tyrell",
    assessedbyOfficer1: "Willas Tyrell",
    assessedbyOfficer2: "Garlan Tyrell",
    assessedbyAOLeader: "Alester Tyrell",
    assessedbyAOOfficer: "Osmund Baratheon",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 8,
    name: "King's Landing",
    email: "dragon@email.com",
    phoneNumber: "123456789",
    contactPerson: "Aerys Targeryen",
    address: "The Crownlands",
    tradeArea: "Ruling Men",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "The Crownlands",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Rhaegar Targeryen",
    assessedbyOfficer1: "Viserys Targeryen",
    assessedbyOfficer2: "Daenerys Targeryen",
    assessedbyAOLeader: "Aegon Targeryen",
    assessedbyAOOfficer: "Aemon Targeryen",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
  {
    id: 9,
    name: "Sunspear",
    email: "sand@email.com",
    phoneNumber: "123456789",
    contactPerson: "Doran Martell",
    address: "Dorne",
    tradeArea: "Viper rearing",
    tools: "Ice, Spears, Shields",
    equipment: "Forges",
    numberOfInstructors: "3",
    state: "Dorne",
    bank: "Iron Bank of Bravos",
    accountNumber: "1234567890",
    bvn: "1234569870",
    assessedbyTeamLeader: "Oberyn Martell",
    assessedbyOfficer1: "Nymeria Martell",
    assessedbyOfficer2: "Maron Martell",
    assessedbyAOLeader: "Elia Martell",
    assessedbyAOOfficer: "Mors Martell",
    yearAssessed: "2019",
    yearReAssessed: "2021",
    operationalStatus: "Active",
  },
];

export default centreData;
