const traineeData = [
  {
    id: 1,
    name: " Jon Snow",
    email: "jon@email.com",
    phoneNumber: "08036086885",
    dob: "21-05-1992",
    gender: "Male",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Killing Wildings",
    state: "Plateau",
    centre: "The Wall",
    year: "2018",
  },
  {
    id: 2,
    name: "Lannister Cersei",
    email: "cersei@email.com",
    phoneNumber: "08012345678",
    dob: "22-05-1992",
    gender: "Female",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Sitting on the iron throne",
    state: "Edo",
    centre: "Kingslanding",
    year: "2015",
  },
  {
    id: 3,
    name: "Lannister Jaime",
    email: "jaime@email.com",
    phoneNumber: "08012345679",
    dob: "21-02-1991",
    gender: "Male",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Protecting the king",
    state: "Edo",
    centre: "Casterly Rock",
    year: "2019",
  },
  {
    id: 4,
    name: "Stark Arya",
    email: "arya@email.com",
    phoneNumber: "080312654789",
    dob: "18-06-1990",
    gender: "Female",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "girl with no face",
    state: "Kogi",
    centre: "Nowhere",
    year: "2022",
  },
  {
    id: 5,
    name: "Targaryen Daenerys",
    email: "daenerys@email.com",
    phoneNumber: "0814789652",
    dob: "17-08-1989",
    gender: "Female",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Mother of dragons",
    state: "Benue",
    centre: "Dragonstone",
    year: "2019",
  },
  {
    id: 6,
    name: "Melisandre Greyworm",
    email: "melisandre@email.com",
    phoneNumber: "0814789634",
    dob: "23-04-1999",
    gender: "Female",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Former slave",
    state: "Imo",
    centre: "Winterfell",
    year: "2017",
  },
  {
    id: 7,
    name: "Clifford Ferrara",
    email: "ferrara@email.com",
    phoneNumber: "0814659652",
    dob: "17-10-1999",
    gender: "Male",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Mountain climbing",
    state: "Taraba",
    centre: "Storms end",
    year: "2015",
  },
  {
    id: 8,
    name: "Frances Rossini",
    email: "rossini@email.com",
    phoneNumber: "0815089652",
    dob: "15-01-1980",
    gender: "male",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Wine tasting",
    state: "Anambra",
    centre: "Wine cellar",
    year: "2017",
  },
  {
    id: 9,
    name: "Roxie Harvey",
    email: "harvey@email.com",
    phoneNumber: "0814710652",
    dob: "07-08-1989",
    gender: "Female",
    disability: false,
    disabilityType: "None",
    address: "Somewhere in Westeros",
    sip: "NISDP",
    tradeArea: "Game host",
    state: "Oyo",
    centre: "Comedy Central",
    year: "2017",
  },
];

export default traineeData;
