const state = [
  { identifier: "Abia", id: 1 },
  { identifier: "Adamawa", id: 2 },
  { identifier: "Akwa Ibom", id: 3 },
  { identifier: "Anambra", id: 4 },
  { identifier: "Bauchi", id: 5 },
  { identifier: "Bayelsa", id: 6 },
  { identifier: "Benue", id: 7 },
  { identifier: "Borno", id: 8 },
  { identifier: "Cross River", id: 9 },
  { identifier: "Delta", id: 10 },
  { identifier: "Ebonyi", id: 11 },
  { identifier: "Edo", id: 12 },
  { identifier: "Ekiti", id: 13 },
  { identifier: "Enugu", id: 14 },
  { identifier: "Gombe", id: 15 },
  { identifier: "Imo", id: 16 },
  { identifier: "Jigawa", id: 17 },
  { identifier: "Kaduna", id: 18 },
  { identifier: "Kano", id: 19 },
  { identifier: "Katsina", id: 20 },
  { identifier: "Kebbi", id: 21 },
  { identifier: "Kogi", id: 22 },
  { identifier: "Kwara", id: 23 },
  { identifier: "Lagos", id: 24 },
  { identifier: "Nasarawa", id: 25 },
  { identifier: "Niger", id: 26 },
  { identifier: "Ogun", id: 27 },
  { identifier: "Ondo", id: 28 },
  { identifier: "Osun", id: 29 },
  { identifier: "Oyo", id: 30 },
  { identifier: "Plateau", id: 31 },
  { identifier: "Rivers", id: 32 },
  { identifier: "Sokoto", id: 33 },
  { identifier: "Taraba", id: 34 },
  { identifier: "Yobe", id: 35 },
  { identifier: "Zamfara", id: 36 },
  { identifier: "FCT", id: 37 },
];

export default state;
